apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: guess.dev
      http:
        paths:
          - path: /matches
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 8000
